SELECT C.COMPANY_CODE, C.FOUNDER,
        (SELECT COUNT(DISTINCT LM.LEAD_MANAGER_CODE) FROM LEAD_MANAGER LM WHERE LM.COMPANY_CODE = C.COMPANY_CODE),
        (SELECT COUNT(DISTINCT SM.SENIOR_MANAGER_CODE) FROM SENIOR_MANAGER SM WHERE SM.COMPANY_CODE = C.COMPANY_CODE),
        (SELECT COUNT(DISTINCT M.MANAGER_CODE) FROM MANAGER M WHERE M.COMPANY_CODE = C.COMPANY_CODE),
        (SELECT COUNT(DISTINCT E. EMPLOYEE_CODE) FROM EMPLOYEE E WHERE E.COMPANY_CODE = C.COMPANY_CODE)
FROM COMPANY C
ORDER BY C.COMPANY_CODE;