SELECT A.START_DATE, MIN(B.END_DATE) AS X
FROM
    (SELECT START_DATE FROM PROJECTS WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)) AS A,
    (SELECT END_DATE FROM PROJECTS WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)) AS B
WHERE A.START_DATE < B.END_DATE
GROUP BY A.START_DATE
ORDER BY DATEDIFF(MIN(B.END_DATE), A.START_DATE), A.START_DATE;